version: '3'
services:
  ${PROJECT_NAME}-nginx:
    container_name: ${PROJECT_NAME}-nginx
    image: '${PROJECT_NAME}-nginx:latest'
    restart: always
    environment:
      - SERVICE_NAME=nginx
    env_file:
      - .env
    volumes:
      - ./.docker/ssl:/etc/nginx/ssl
      - ./.docker/nginx/custom-files:/etc/nginx/custom-files
    networks:
      - consul
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
networks:
  consul:
    external:
      name: consul
