version: '3'
services:
  ${PROJECT_NAME}-blue:
    container_name: ${PROJECT_NAME}-blue
    stdin_open: true
    tty: true
    image: ${PROJECT_NAME}:blue
    restart: always
    networks:
      - consul
    extra_hosts:
      - "${HOST_IP}:host-gateway"
    environment:
      - SERVICE_NAME=blue
    env_file:
      - .env
    volumes: []
  ${PROJECT_NAME}-green:
    container_name: ${PROJECT_NAME}-green
    stdin_open: true
    tty: true
    image: ${PROJECT_NAME}:green
    restart: always
    networks:
      - consul
    extra_hosts:
      - "${HOST_IP}:host-gateway"
    environment:
      - SERVICE_NAME=green
    env_file:
      - .env
    volumes: []
networks:
  consul:
    external:
      name: consul
